# Generated by Django 4.2.9 on 2024-01-25 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pybo", "0005_answer_voter_question_voter_alter_answer_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modify_date", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_comment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voter",
                    models.ManyToManyField(
                        related_name="voter_comment", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="answer",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="comments_answer", to="pybo.comment"
            ),
        ),
    ]
