# Generated by Django 4.2.9 on 2024-01-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pybo", "0006_comment_answer_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
